### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with index 3

### ISSUE THREAD

**Issue by Udyz** [nirajxhrestha/EduMail-Generator#2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\EduMail-Generator-master\bot.py", line 1058, in <module>
    main()
  File "C:\Users\Administrator\Desktop\EduMail-Generator-master\bot.py", line 1055, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "C:\Users\Administrator\Desktop\EduMail-Generator-master\bot.py", line 471, in start_bot
    dropdown_menu.select_by_index(random.randint(1,4))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\select.py", line 103, in select_by_index
    raise NoSuchElementException("Could not locate element with index %d" % index)
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with index 3

**Comment by nirajxhrestha** [comment]
don't run is from Administrator user location 
also please check if all the dependencies are installed
pip install (dependency name)
