### ISSUE TITLE
When running setup.py

### ISSUE THREAD

**Issue by SandeepParmar-RKU** [nirajxhrestha/EduMail-Generator#6]
Firefox
Traceback (most recent call last):
  File "C:\Users\sandi\Desktop\EduMail-Generator-master\setup.py", line 70, in <module>
    main()
  File "C:\Users\sandi\Desktop\EduMail-Generator-master\setup.py", line 25, in main
    firefox_ver = get_firefox_version()
  File "C:\Users\sandi\Desktop\EduMail-Generator-master\__dwnldDrivers\versions.py", line 73, in get_firefox_version
    platform, _ = get_platform_architecture_firefox()
  File "C:\Users\sandi\Desktop\EduMail-Generator-master\__dwnldDrivers\versions.py", line 50, in get_platform_architecture_firefox
    architecture = os_arch()
  File "C:\Users\sandi\Desktop\EduMail-Generator-master\__dwnldDrivers\versions.py", line 29, in os_arch
    output = subprocess.check_output(['wmic', 'os', 'get', 'OSArchitecture'])
  File "C:\Users\sandi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\sandi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\sandi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\sandi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nirajxhrestha** [comment]
try installing chrome and update the chrome-driver with your chrome version

**Comment by SandeepParmar-RKU** [comment]
so i downloaded latest chrome driver and replaced it in your web driver folder(changed the .exe) still not solved
